// <auto-generated />
using System;
using Falchion.Villains.Vault.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Falchion.Villains.Vault.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.CommunityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("CommunityEvents", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.CommunityParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityRaceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsChallenge")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDls")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpectator")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CommunityRaceId", "UserId")
                        .IsUnique();

                    b.ToTable("CommunityParticipations", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.CommunityRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CommunityEventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Distance")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<bool>("HasVirtualOption")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKilometers")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPartOfChallenge")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CommunityEventId");

                    b.HasIndex("RaceDate");

                    b.ToTable("CommunityRaces", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DivisionLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DivisionValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId", "DivisionValue")
                        .IsUnique();

                    b.ToTable("Divisions", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.DlsDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BibNumber")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DlsRaceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFirstDls")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoingForKills")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DlsRaceId");

                    b.HasIndex("UserId");

                    b.HasIndex("DlsRaceId", "BibNumber")
                        .IsUnique()
                        .HasFilter("[BibNumber] IS NOT NULL");

                    b.HasIndex("DlsRaceId", "UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("DlsDeclarations", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.DlsRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RaceDate");

                    b.HasIndex("RaceId");

                    b.ToTable("DlsRaces", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EventSeries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("TrackShackUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EventSeries");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("TrackShackUrl")
                        .IsUnique();

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CancellationRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("ProgressDataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RaceId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.NotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CommunityEvents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("DlsDeclarations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("RaceResults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.PushToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushTokens");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Distance")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("EventSeries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatisticsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackShackUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WeatherDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("EventSeries");

                    b.HasIndex("TrackShackUrl")
                        .IsUnique();

                    b.HasIndex("RaceDate", "Distance");

                    b.ToTable("Races", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.RaceResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BibNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("ClockTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int?>("DivisionPlace")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("GenderPlace")
                        .HasColumnType("int");

                    b.Property<string>("Hometown")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan?>("NetTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OverallPace")
                        .HasColumnType("time");

                    b.Property<int?>("OverallPlace")
                        .HasColumnType("int");

                    b.Property<int?>("Passers")
                        .HasColumnType("int");

                    b.Property<int?>("Passes")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("ResultDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunnerType")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Split1")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Split10")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Split2")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Split3")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Split4")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Split5")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Split6")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Split7")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Split8")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Split9")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("Hometown");

                    b.HasIndex("Name");

                    b.HasIndex("RaceId", "BibNumber")
                        .IsUnique();

                    b.HasIndex("RaceId", "Gender");

                    b.HasIndex("RaceId", "Hometown");

                    b.HasIndex("RaceId", "NetTime");

                    b.HasIndex("RaceId", "OverallPlace");

                    b.HasIndex("RaceId", "StartTime");

                    b.HasIndex("RaceId", "Name", "Age");

                    b.ToTable("RaceResults", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.RaceResultFollow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool?>("DeadLastStarted")
                        .HasColumnType("bit");

                    b.Property<int>("FollowType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("RaceResultId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceResultId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RaceResultId")
                        .IsUnique();

                    b.ToTable("RaceResultFollows", (string)null);
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.CommunityEvent", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.CommunityParticipation", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.CommunityRace", "CommunityRace")
                        .WithMany("Participations")
                        .HasForeignKey("CommunityRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunityRace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.CommunityRace", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.CommunityEvent", "CommunityEvent")
                        .WithMany("Races")
                        .HasForeignKey("CommunityEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunityEvent");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Division", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.Race", "Race")
                        .WithMany("Divisions")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.DlsDeclaration", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.DlsRace", "DlsRace")
                        .WithMany("Declarations")
                        .HasForeignKey("DlsRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DlsRace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.DlsRace", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Event", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Job", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.Race", "Race")
                        .WithMany("Jobs")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.NotificationPreference", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.PushToken", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Race", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.Event", "Event")
                        .WithMany("Races")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.RaceResult", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.Division", "Division")
                        .WithMany("Results")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.Race", "Race")
                        .WithMany("Results")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.RaceResultFollow", b =>
                {
                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.RaceResult", "RaceResult")
                        .WithMany()
                        .HasForeignKey("RaceResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Falchion.Villains.Vault.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaceResult");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.CommunityEvent", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.CommunityRace", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Division", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.DlsRace", b =>
                {
                    b.Navigation("Declarations");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Event", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("Falchion.Villains.Vault.Api.Data.Entities.Race", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("Jobs");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
