/**
 * Link Utilities for MarkdownViewer
 *
 * Detects Villains Vault app URLs and converts them to in-app
 * navigation paths so users stay inside the app instead of
 * being redirected to an external browser.
 */

import type { Router } from 'expo-router';

/** The production domain used in links generated by MCP tools. */
const APP_DOMAIN = 'vault.villains.run';

/**
 * Route patterns that map external URL path segments to in-app paths.
 * Web: used as href values (e.g. "/race/5") — must NOT include route groups like (tabs).
 * Native: used with router.push which also resolves clean paths correctly.
 */
const DEEP_LINK_ROUTES: Record<string, string> = {
	'race': '/race',
	'results': '/results',
};

/**
 * If `url` points to the Villains Vault app, returns the corresponding
 * in-app path (e.g. `"/(tabs)/race/5"`). Returns `null` for external URLs.
 */
export function getInAppPath(url: string): string | null {
	try {
		const parsed = new URL(url, 'https://placeholder.invalid');

		// Only intercept our own domain
		if (parsed.hostname !== APP_DOMAIN) {
			return null;
		}

		// Strip leading slash and split: "/race/5" → ["race", "5"]
		const segments = parsed.pathname.replace(/^\//, '').split('/').filter(Boolean);

		if (segments.length >= 2) {
			const routeBase = DEEP_LINK_ROUTES[segments[0]];
			if (routeBase) {
				return `${routeBase}/${segments[1]}`;
			}
		}

		return null;
	} catch {
		return null;
	}
}

/**
 * Attempts to navigate to an in-app route for the given URL.
 * Returns `true` if the URL was handled internally, `false` otherwise.
 */
export function tryNavigateInApp(url: string, router: Router): boolean {
	const path = getInAppPath(url);
	if (path) {
		router.push(path as any);
		return true;
	}
	return false;
}
